import type {
  TimeOffRequest,
  TimeOffBalance,
} from "@/services/query/time-attendance/time-attendance.types";

export const INITIAL_BALANCES: TimeOffBalance[] = [
  {
    leaveTypeId: "lt_1",
    leaveTypeName: "Annual Leave",
    allocated: 15,
    consumed: 4,
    pendingApproval: 2,
    remaining: 9,
  },
  {
    leaveTypeId: "lt_2",
    leaveTypeName: "Sick Leave",
    allocated: 10,
    consumed: 2,
    pendingApproval: 0,
    remaining: 8,
  },
  {
    leaveTypeId: "lt_3",
    leaveTypeName: "Casual Leave",
    allocated: 7,
    consumed: 1,
    pendingApproval: 1,
    remaining: 5,
  },
];

export const INITIAL_REQUESTS: TimeOffRequest[] = [
  {
    id: "req_1",
    employeeId: "emp_1",
    employeeName: "Anuroop TM",
    leaveTypeId: "lt_1",
    leaveTypeName: "Annual Leave",
    startDate: "2026-06-15",
    endDate: "2026-06-18",
    halfDay: false,
    reason: "Family vacation trip",
    status: "pending",
    createdAt: "2026-06-01",
  },
  {
    id: "req_2",
    employeeId: "emp_1",
    employeeName: "Anuroop TM",
    leaveTypeId: "lt_2",
    leaveTypeName: "Sick Leave",
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    halfDay: true,
    halfDaySession: "morning",
    reason: "Dental checkup and extraction",
    status: "approved",
    approvedBy: "m_1",
    approvedByName: "Supervisor Jane",
    approvedAt: "2026-05-12",
    createdAt: "2026-05-11",
  },
  {
    id: "req_3",
    employeeId: "emp_1",
    employeeName: "Anuroop TM",
    leaveTypeId: "lt_3",
    leaveTypeName: "Casual Leave",
    startDate: "2026-04-05",
    endDate: "2026-04-06",
    halfDay: false,
    reason: "Personal urgent matters",
    status: "approved",
    approvedBy: "m_1",
    approvedByName: "Supervisor Jane",
    approvedAt: "2026-04-04",
    createdAt: "2026-04-03",
  },
];
